import os

KAFKA_URL = os.getenv("KAFKA_URL")
TOPIC_EPISODE_METADATA = os.getenv("TOPIC_EPISODE_METADATA")
SPARK_URL = os.getenv("SPARK_URL")
DELTA_PATH_EPISODES = os.getenv("DELTA_PATH_EPISODES")
DELTA_PATH_TRANSCRIPTS = os.getenv("DELTA_PATH_TRANSCRIPTS")