import os

KAFKA_URL = os.getenv("KAFKA_URL")
TOPIC_EPISODES_ID = os.getenv("TOPIC_EPISODES_ID")
TOPIC_EPISODE_METADATA = os.getenv("TOPIC_EPISODE_METADATA")
TOPIC_USER_EVENTS_STREAMING = os.getenv("TOPIC_USER_EVENTS_STREAMING")

DELTA_EVENTS_PATH = os.getenv("DELTA_EVENTS_PATH") 
DELTA_PATH_EPISODES = os.getenv("DELTA_PATH_EPISODES")
DELTA_PATH_TRANSCRIPTS = os.getenv("DELTA_PATH_TRANSCRIPTS")
DELTA_PATH_VECTORS = os.getenv("DELTA_PATH_VECTORS")
DELTA_PATH_SIMILARITIES = os.getenv("DELTA_PATH_SIMILARITIES")
DELTA_PATH_DAILY = os.getenv("DELTA_PATH_DAILY")
DELTA_RAW_USER_EVENTS_PATH = os.getenv("DELTA_RAW_USER_EVENTS_PATH")

API_PODCAST_INDEX_KEY = os.getenv("API_PODCAST_INDEX_KEY")
API_PODCAST_INDEX_SECRET= os.getenv("API_PODCAST_INDEX_SECRET")

SAMPLE_EPISODES_JSON_PATH = os.getenv("SAMPLE_EPISODES_JSON_PATH")
N_EVENTS_PER_USER = int(os.getenv("N_EVENTS_PER_USER"))

MONGO_URI = os.getenv("MONGO_URI")
MONGO_DB = os.getenv("MONGO_DB")
MONGO_COLLECTION_SIMILARITIES = os.getenv("MONGO_COLLECTION_SIMILARITIES")
MONGO_COLLECTION_USER_EVENTS_TRAINING = os.getenv("MONGO_COLLECTION_USER_EVENTS_TRAINING")
MONGO_COLLECTION_FINAL_RECS = os.getenv("MONGO_COLLECTION_FINAL_RECS")
MONGO_COLLECTION_USER_HISTORY = os.getenv("MONGO_COLLECTION_USER_HISTORY")
MONGO_COLLECTION_USERS = os.getenv("MONGO_COLLECTION_USERS")

NUM_USERS = int(os.getenv("NUM_USERS"))
MIN_EPS_PER_USER = int(os.getenv("MIN_EPS_PER_USER"))
MAX_EPS_PER_USER = int(os.getenv("MAX_EPS_PER_USER"))
EPISODE_LIMIT = int(os.getenv("EPISODE_LIMIT"))
EPISODE_SAMPLE_N = int(os.getenv("EPISODE_SAMPLE_N"))

ALS_MODEL_PATH = os.getenv("ALS_MODEL_PATH")
N_FINAL_RECOMMENDATION = int(os.getenv("N_FINAL_RECOMMENDATION"))
N_RECOMMENDATION_FOR_USER = int(os.getenv("N_RECOMMENDATION_FOR_USER"))
USER_EVENT_STREAM= os.getenv("USER_EVENT_STREAM")