import os

KAFKA_URL = os.getenv("KAFKA_URL")
TOPIC_EPISODES_ID = os.getenv("TOPIC_EPISODES_ID")
TOPIC_EPISODE_METADATA = os.getenv("TOPIC_EPISODE_METADATA")

SPARK_URL = os.getenv("SPARK_URL")
DELTA_PATH_EPISODES = os.getenv("DELTA_PATH_EPISODES")
DELTA_PATH_TRANSCRIPTS = os.getenv("DELTA_PATH_TRANSCRIPTS")
DELTA_PATH_VECTORS = os.getenv("DELTA_PATH_VECTORS")
DELTA_PATH_SIMILARITIES = os.getenv("DELTA_PATH_SIMILARITIES")

API_PODCAST_INDEX_KEY = os.getenv("API_PODCAST_INDEX_KEY")
API_PODCAST_INDEX_SECRET= os.getenv("API_PODCAST_INDEX_SECRET")

SAMPLE_EPISODES_JSON_PATH = os.getenv("SAMPLE_EPISODES_JSON_PATH")

MONGO_URI = os.getenv("MONGO_URI")
MONGO_DB = os.getenv("MONGO_DB")
MONGO_COLLECTION_SIMILARITIES = os.getenv("MONGO_COLLECTION_SIMILARITIES")
